AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  pKeyName:
    Type: String   
  pInstanceName:
    Type: String
  pAMIId:
    Type: String
  pInstanceType:
    Type: String
    AllowedValues:
      - t2.micro
      - t2.nano
    Default: t2.micro
  pKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"  

Resources:
   
  rEC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref pAMIId
      KeyName: !Ref pKeyPair
      InstanceType: "t2.nano"
      Tags:
        - Key: "Name"
          Value: !Ref pInstanceName
        - Key: "Type"
          Value: !Ref pKeyName     


Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref rEC2Instance1         
